### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by KasperH2** [liaoherui/VirStrain#8]
When I run VirStrain on a specific fastq file I get this error. Do you know what causes it? The file should seem like a bunch of other fastq files in a cohort I'm using, but something causes an issue with this one file:

bin/S3_Strain_pred_My_Method_V0819_Val.py:150: RuntimeWarning: invalid value encountered in true_divide
  weighted_freq_arr=freq_arr/np.sum(freq_arr)
Traceback (most recent call last):
  File "bin/S3_Strain_pred_My_Method_V0819_Val.py", line 290, in <module>
    pre_freq_arr=pre_freq_arr[keep]
IndexError: list index out of range

The zipped file is 98 MB, so can't directly upload it

**Comment by liaoherui** [comment]
Hi, KasperH2,
Have you checked whether the targeted virus species does exist in this fastq file? Based on the log, I think this error may be caused by the absence of the strain of the target virus species in the sequencing data. 

However, if you are pretty sure there must be the viral strains in the fastq file, then you can replace the original "bin/S3_Strain_pred_My_Method_V0819_Val.py" with the attached one and tell me what log you can get.  Thanks!

[S3_Strain_pred_My_Method_V0819_Val.zip](https://github.com/liaoherui/VirStrain/files/9959231/S3_Strain_pred_My_Method_V0819_Val.zip)

**Comment by KasperH2** [comment]
This might of course be the case. Good to know that this error could be because of that. I tried anyways and got this:
[False False False ... False False False]
[1 1 2 2 1 1 1 1 1 1 1 1]

Thank you

**Comment by liaoherui** [comment]
Hi, KasperH2,
Based on your output, I think there is a very high probability that the data does not contain the target virus, or that the abundance of the target virus is so low that VirStrain cannot detect the strain.

**Comment by KasperH2** [comment]
Thanks for quick replies
